### PR TITLE
change language when we select language in dropdown menu

### PR DESCRIPTION
**Pull request by jaswanthkasani**
added multi language functionality, added copy button, updated UI interface and published the website

### CODE REVIEW

**Comment by AmirSalari** [comment]
Hey Jaswanth, thanks I am reading the code now and we will merge it.

Just if you guys want to test a pull request locally before merging it, you can use this command:

`git fetch origin pull/<pull request ID>/head:<branch name> && git checkout FETCH_HEAD`

the pull request id is near to its title (in this case 39)

**Comment by OmarAlAkkad** [comment]
Dear Jaswanth,

I checked your code and the published server and everything works as intended.

**Comment by cemilcan98** [comment]
Hey Guys, thank you Jaswanth,  I check the changes and I didn't see a problem with it, so we can merge it if you agree.

**Comment by jaswanthkasani** [comment]
Hey guys!! Glad to hear that there are no flaws in my code!! Once I get
home, I’ll deploy the main branch into the server

**Pull request merged**
